### ISSUE TITLE
question: Response objects in serinus

### ISSUE THREAD

**Issue by mjablecnik** [francescovallone/serinus#80]
Hello, I compare serinus with shelf and I have this question:

Does Serinus support response objects same as shelf_plus? 

For example shelf_plus support:

```
  var app = Router().plus;

  app.get('/text', () => 'a text');

  app.get('/binary', () => File('data.zip').openRead());

  app.get('/json', () => {'name': 'John', 'age': 42});

  app.get('/class', () => Person('Theo'));

  app.get('/list-of-classes', () => [Person('Theo'), Person('Bob')]);

  app.get('/iterables', () => [1, 10, 100].where((n) => n > 9));

  app.get('/handler', () => typeByExtension('html') >> '<h1>Hello</h1>');

  app.get('/file', () => File('thesis.pdf'));
```

So when I return File or some class or json, does Serinus have the same behavior?

**Comment by francescovallone** [comment]
Hello, yes Serinus from the version 0.6 (PR #54) allows to return values directly. If you want to return a class it must use the mixin `JsonObject` so that it can be parsable as a json object 😄

**Comment by mjablecnik** [comment]
Could you show me some example for return json, class and file objects in Serinus?

**Comment by francescovallone** [comment]
Yes of course!

All of them are listed in this [test](https://github.com/francescovallone/serinus/blob/main/packages/serinus/test/http/responses_test.dart). Let me know if it is enough or if you wanted something else 😄

**Comment by mjablecnik** [comment]
Yes, it is exactly what I wanted to see.. :)
