### ISSUE TITLE
question: Parameter parsing

### ISSUE THREAD

**Issue by mjablecnik** [francescovallone/serinus#81]
Hello, I compare serinus with shelf and I have this question:
Does Serinus support parsing parameter from path similar as shelf_router:
```
app.get('/user/<user>', (Request request, String user) {
  return Response.ok('hello $user');
});
```
Where you can have user variable added into method.

In Serinus documentation I see that I have to write `context.params['name']` for access to params:
```
on(Route.get('/<id>/<name>'), (context) async {
      return 'Hello ${context.params['name']} with id ${context.params['id']}!';
    });
```

And also parsing object from body of POST would be fine to support:

For example when I send this json in body:
```
{
  "name": "John",
  "surname": "Doe",
  "email": "john.doe@gmail.com",
  "phone": "+420 467 738 275",
  "is_verified": true,
  "age": 27,
}
```

It would be good to automatically parse into User class.

**Comment by francescovallone** [comment]
Hello, I will go by points:
- The same thing will be available when the feat #74 will be merged. After the merge I will probably release a dev version for the 1.0.
- This is something I would like to work on, 1.0 is also designed for changes like this that would go a long way in helping users.

**Comment by mjablecnik** [comment]
Ok, so I will wait then you release version 1.0.0
Do you have some expectation when it could be? :)

**Comment by francescovallone** [comment]
I would like to fully release it at the end of october probably. But after some of the biggest changes I will release some pre-release versions 😃

**Comment by mjablecnik** [comment]
Ok, when you will have ready 1.0.0 in beta stage, I will try it and test it.
I would like to use Serinus in some my future projects but I want to work with stable version. :)

**Comment by francescovallone** [comment]
I will close this issue for now. But feel free to reopen it. 😁
