### ISSUE TITLE
question: Support parsing multipart and form-data requests 

### ISSUE THREAD

**Issue by mjablecnik** [francescovallone/serinus#82]
Do you support something like: shelf_multipart?

**Comment by francescovallone** [comment]
Yep, multipart and url-encoded form data requests are supported. To access the values inside the form you can use the following 
```dart
    on(Route.post(path: '/'), (RequestContext context) async {
      final formData = context.body.formData.values;
      return 'Hello World!';
    });
```

**Comment by mjablecnik** [comment]
Ok. I didn't find it in documentation so I didn't know if you support it or not.. :)

**Comment by francescovallone** [comment]
Yep I can understand the confusion 😄 I will add them to the documentation in a specific page!
